name: Test GHA (this workflow should pass)

on: [workflow_dispatch, push]

jobs:
    test-gha:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            # This step should pass
            - name: AWS Auth
              uses: ethanrucinski/action-aws-oidc-auth@main
              with:
                initial-role-to-assume: arn:aws:iam::403707884266:role/github-oidc-role
                aws-region: us-east-2
                lambda-function-name: github-oidc-auth
            - name: Test final creds
              run: aws sts get-caller-identity
