name: Test GHA

on: [workflow_dispatch, push]

jobs:
  test-gha:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Get Token
        uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            console.log(token);
      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::403707884266:role/Github-Actions-Role-403707884266
          aws-region: us-east-2
      - name: Validate test
        run: aws sts get-caller-identity
